site_name: Tanki Wiki
site_url: https://gtafanwrld.github.io/tanki-wiki/
theme:
  theme:
  logo: assets/logo.gif
  name: material
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep orange
      accent: orange
    - media: "(prefers-color-scheme: dark)"
      scheme: slate 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode    
      primary: deep orange
      accent: orange

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Purchases: payment_ways.md
  - Rebalances: buffs_nerfs.md
  - Mods: mods.md
  - About: about.md
  # etc.
